[bot]
token = YOUR_TELEGRAM_BOT_TOKEN
debug = false

[database]
# sqlite | postgres | mysql
driver = sqlite

# SQLite
sqlite_path = data/bot.db

# Postgres
pg_user = postgres
pg_password = password
pg_host = localhost
pg_port = 5432
pg_db = botdb

# MySQL
mysql_user = root
mysql_password = password
mysql_host = localhost
mysql_port = 3306
mysql_db = botdb

[art_source]
base_url = https://e621.net
username = YOUR_USERNAME
api_key = YOUR_API_KEY

[watch]
check_every_seconds = 90

[autoposting]
enabled = false
check_every_seconds = 60
; Set to -100 to disable specific rating
channel_id_safe = -100
channel_id_questionable = -100
channel_id_explicit = -100
score_limit = 50
post_limit = 50

; You can run Redis server in docker. Read more here: https://github.com/kararasenok-gd/e621monitor/#3-redis-server-for-caching
[redis]
host=localhost
port=6379
db=0
username=
pass=